version: '2'
services:

  composer:
    image: ypereirareis/composer:1.1.3-alpine
    working_dir: /src
    environment:
      COMPOSER_HOME: /tmp/.composer
    volumes:
      - ~/.composer:/tmp/.composer:rw
      - ./sf:/src:rw

  php:
    build: ./docker/php
    environment:
      SYMFONY_ENV:
      CUSTOM_UID: ${UID}
    volumes:
      - ./var/logs/app:/var/www/html/var/logs:rw
      - ./sf:/var/www/html:rw
    networks:
      - default

  rabbit1:
    image: harbur/rabbitmq-cluster
    hostname: rabbit1
    environment:
      ERLANG_COOKIE: 'ck8FC0uJ9vePIhLr'
      TCP_PORTS: "5672,15672"
    ports:
      - "127.0.0.1:1234:15672"
    networks:
      - rabbit_1_2
      - rabbit_3_1

  rabbit2:
    image: harbur/rabbitmq-cluster
    hostname: rabbit2
    environment:
      ERLANG_COOKIE: 'ck8FC0uJ9vePIhLr'
      CLUSTER_WITH: rabbit1
      TCP_PORTS: "5672"
    ports:
      - "127.0.0.1:1235:15672"
    networks:
      - rabbit_1_2
      - rabbit_2_3

  rabbit3:
    image: harbur/rabbitmq-cluster
    hostname: rabbit3
    environment:
      ERLANG_COOKIE: 'ck8FC0uJ9vePIhLr'
      CLUSTER_WITH: rabbit1
      TCP_PORTS: "5672"
    ports:
      - "127.0.0.1:1236:15672"
    networks:
      - rabbit_3_1
      - rabbit_2_3

  haproxy:
    image: dockercloud/haproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      MODE: tcp
    expose:
      - 5672
    links:
      - rabbit1
      - rabbit2
      - rabbit3
    ports:
      - '80:80'
      - '5672:5672'
    networks:
      - default
      - rabbit_1_2
      - rabbit_2_3
      - rabbit_3_1

networks:
  rabbit_1_2:
    external:
      name: rabbit_1_2
  rabbit_2_3:
    external:
      name: rabbit_2_3
  rabbit_3_1:
    external:
      name: rabbit_3_1
