version: '2'
services:

  composer:
    image: ypereirareis/composer:1.1.3-alpine
    working_dir: /src
    environment:
      COMPOSER_HOME: /tmp/.composer
    volumes:
      - ~/.composer:/tmp/.composer:rw
      - ./sf:/src:rw

  php:
    build: ./docker/php
    restart: always
    environment:
      SYMFONY_ENV:
      CUSTOM_UID: ${UID}
    volumes:
      - ./var/logs/app:/var/www/html/var/logs:rw
      - ./sf:/var/www/html:rw

  rabbitmq1:
    image: harbur/rabbitmq-cluster
    hostname: rabbitmq1
    environment:
      RABBITMQ_DEFAULT_USER: rbu
      RABBITMQ_DEFAULT_PASS: rbp
      ERLANG_COOKIE: 'ck8FC0uJ9vePIhLr'
      TCP_PORTS: "5672"
    ports:
      - "127.0.0.1:1234:15672"

  rabbitmq2:
    image: harbur/rabbitmq-cluster
    hostname: rabbitmq2
    environment:
      RABBITMQ_DEFAULT_USER: rbu
      RABBITMQ_DEFAULT_PASS: rbp
      ERLANG_COOKIE: 'ck8FC0uJ9vePIhLr'
      CLUSTER_WITH: rabbitmq1
      TCP_PORTS: "5672"
    ports:
      - "127.0.0.1:1235:15672"

  rabbitmq3:
    image: harbur/rabbitmq-cluster
    hostname: rabbitmq3
    environment:
      RABBITMQ_DEFAULT_USER: rbu
      RABBITMQ_DEFAULT_PASS: rbp
      ERLANG_COOKIE: 'ck8FC0uJ9vePIhLr'
      CLUSTER_WITH: rabbitmq1
      TCP_PORTS: "5672"
    ports:
      - "127.0.0.1:1236:15672"

  haproxy:
    image: dockercloud/haproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      MODE: tcp
    links:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - '80:80'
      - '5672:5672'


