
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error

swarrot:
    provider: pecl #amqp_lib
    default_connection: rabbitmq
    default_command: swarrot.command.base
    connections:
        rabbitmq1:
            host: rabbitmq1
            port: 5672
            login: guest
            password: guest
            vhost: '/'
        rabbitmq2:
            host: rabbitmq2
            port: 5672
            login: guest
            password: guest
            vhost: '/'
        rabbitmq3:
            host: rabbitmq3
            port: 5672
            login: guest
            password: guest
            vhost: '/'
    consumers:
        test_consume_quickly: # name of the consumer
            processor: processor.test_consume_quickly # name of the service
            extras:
                poll_interval: 500000
                requeue_on_error: false
            middleware_stack:
                - configurator: swarrot.processor.signal_handler
                - configurator: swarrot.processor.max_messages
                  extras:
                    max_messages: 10
                - configurator: swarrot.processor.max_execution_time
                  extras:
                    max_execution_time: 30
                - configurator: swarrot.processor.memory_limit
                  extras:
                      memory_limit: 50
                - configurator: swarrot.processor.exception_catcher
                - configurator: swarrot.processor.ack
                - configurator: swarrot.processor.retry
                  extras:
                    retry_exchange: 'retry'
                    retry_attempts: 3
                    retry_routing_key_pattern: 'benchmark_test_1_retry_%%attempt%%'

    messages_types:
        my_publisher_1:
            connection: rabbitmq1
            exchange: benchmark_test_1
            routing_key: benchmark_test_1

        my_publisher_2:
            connection: rabbitmq2
            exchange: benchmark_test_1
            routing_key: benchmark_test_1

        my_publisher_3:
            connection: rabbitmq3
            exchange: benchmark_test_1
            routing_key: benchmark_test_1
